USE WebShopDB

--CREATING NEW SYSTEM-VERSIONED TABLE
--PRODUCT
CREATE TABLE dbo.TProduct
(
	nProductId INT IDENTITY(1,1) PRIMARY KEY,
	cName VARCHAR(50) NOT NULL,
	cDescription VARCHAR(160) NOT NULL,
	nUnitPrice DECIMAL(5,2) NOT NULL,
	nStock INT NOT NULL,
	nAvgRating DECIMAL (2,1) NOT NULL,
	SysStartTime datetime2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
	SysEndTime datetime2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
	PERIOD FOR SYSTEM_TIME (SysStartTime,SysEndTime)
) 
	WITH (SYSTEM_VERSIONING = ON 
	(HISTORY_TABLE = dbo.TProductHistory, DATA_CONSISTENCY_CHECK = ON));


--RATING
CREATE TABLE dbo.TRating
(
	nRatingId INT IDENTITY(1,1) PRIMARY KEY,
	nProductId INT NOT NULL,
	nUserId INT NOT NULL,
	nRating INT NOT NULL,
	cComment VARCHAR(255) NOT NULL,
	SysStartTime datetime2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
	SysEndTime datetime2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,	
	PERIOD FOR SYSTEM_TIME (SysStartTime,SysEndTime),
	CONSTRAINT FK_nProductId FOREIGN KEY (nProductId) REFERENCES TProduct(nProductId)
) 
	WITH (SYSTEM_VERSIONING = ON 
	(HISTORY_TABLE = dbo.TRatingHistory, DATA_CONSISTENCY_CHECK = ON));


--ALTERING TABLE WHICH ALREADY EXISTS
--PRODUCT
ALTER TABLE TProduct
	ADD 
		SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
			CONSTRAINT DF_SysStart DEFAULT SYSUTCDATETIME(),
		SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
			CONSTRAINT DF_SysEnd DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.99999999'),
		PERIOD FOR SYSTEM_TIME (SysStartTime,SysEndTime);
GO

ALTER TABLE TProduct
	SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TProductHistory));


--RATING
ALTER TABLE TRating
	ADD 
		SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
			CONSTRAINT DF_SysStart2 DEFAULT SYSUTCDATETIME(),
		SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
			CONSTRAINT DF_SysEnd2 DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.99999999'),
		PERIOD FOR SYSTEM_TIME (SysStartTime,SysEndTime);
GO

ALTER TABLE TRating
	SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TRatingHistory));